### ISSUE TITLE
Error running the colab

### ISSUE THREAD

**Issue by songproducer** [robgon-art/CLIPandPASTE#1]
FileNotFoundError: [Errno 2] No such file or directory: 'ai-memer_embeddings16.npy'

**Comment by robgon-art** [comment]
Hi songproducer, thanks for the report. I will check it out...

**Comment by robgon-art** [comment]
I just ran it successfully without making any changes. Here are my output lines that show the successful download of the file.

From: https://drive.google.com/uc?id=1TS5K0BGk5ruCF-bc6yeMSAEb5z8Oi_st
To: /content/ai-memer_embeddings16.npy
100% 691M/691M [00:24<00:00, 28.8MB/s]

Please paste in your output after the first two lines above.

**Comment by songproducer** [comment]
It works today. Thanks!
